language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Jl0GNZ2+Gss7UqAXul8A2vdO8pccoTHNfoY2WxMNUtM9qGicDR6pz93SsDthh0ghMwoxusOt5IjssgKGBgfXd9yQaxfzPhNuRB6hKt1M9o56Ey4xbZIAykMGu48qo1ylR3jwgV3PdwfzVAgfDwoi/UtCSWBC8GNuhmhoZqLJYdTcEvzReKCRMUffgb2tDzCYRaZlAQQMTaxR58VsXDn9hXulBlqLPTiTvcMSbhBgycicEIOLOfAqnCFrdSoUO9zrzcKpU07QuiWJCxTSzQ3n+KhcesYGHjfkdyrCQe6vJkxrzjm1+ETE52/v0lWuCHSOVKnpxLKjqh6tF9xmXRxz5RecUVXnlwWnFpTOuWZJOjXjZnMJD6sgM/UjNgyX2gqdEN0VyM8JDKftWpuqxyiUNmTPz5xqPNh5rdyjepBK7FnsnbRO1SQV8shyH9jcZVp289ZBOE51ByaB5ylTsswGpZBGVGOM6qPWVpdVfHXFi/j5kp1HOnQ9hJo3luyoQcsjL+jXwNUIpHAjhQ3AIVx9IKH6TSYEU2y7P1LqlMHD5QS7vqXwcz6T1CkDBQ6O24HZiOf/AWuQJVZyJ25ZwDq/E9axxj9daM4USs2SCa6T2sbTmuOttCOnrvAAcLIS97Ha3jw2QOlitFWUSHZS5QTeHbFaojEnbJc+agzYDNCJ0qM=
  app: aqueous-basin-13078
  on:
    repo: jsurt/Blog-Challenge-with-Testing-for-Mongo
